# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ElementTable
                                 A QGIS plugin
 This plugin alows to set/unset visibility of layer with chemical data with help of element table widget
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-07
        copyright            : (C) 2020 by Petras Jokubauskas
        email                : p.jokubauskas@uw.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ElementTable class from file ElementTable.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .chemical_selector import ElementTable
    return ElementTable(iface)
